#
# A ConfigMap which contains the configuration of the authservice.
# In bookinfo-with-authservice-template.yaml the authservice container is created
# with this ConfigMap volume mounted inside the container at /etc/authservice, which
# is the location where the authservice expects the file to exist.
#

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-authservice-configmap
data:
  config.json: |
    {
      "listen_address": "127.0.0.1",
      "listen_port": "10003",
      "log_level": "trace",
      "threads": 1,
      "chains": [
        {
          "name": "idp_filter_chain",
          "filters": [
          {
            "oidc":
              {
                "authorization": {
                  "scheme": "https",
                  "hostname": "keycloak.example.com",
                  "path": "/auth/realms/master/protocol/openid-connect/auth",
                  "port": "8443"
                },
                "token": {
                  "scheme": "https",
                  "hostname": "keycloak.example.com",
                  "path": "/auth/realms/master/protocol/openid-connect/token",
                  "port": "8443"
                },
                "jwks": "{\"keys\":[{\"kid\":\"8hdOQpGve5Uyg-6lLeL7p8iAbf5wUBpcGSeZ8DBnMlw\",\"kty\":\"RSA\",\"alg\":\"RS256\",\"use\":\"sig\",\"n\":\"rJDzb-ItxvXHqr3d8A3oCqv5Ec5jb6JirMw8eKxak_bDlU5Pq44ynIKMnJO-EoeqsrMZshUuIwYoCzrhth7ARU_yQKf9UZGhh-cjLIOam3-LOe6h0MciS32x-Vki0iU4QCcibhX3E-epcoNGXzqdQ77YNh3xTwQfRrHPvuAkmHVGx1JDqlK8Grx24n9rWtr3HKY_PoYBEFWjET-7bPs2XCENHzI_2GE9msrO7MOjUIZoWlKPntW38ovkVEgvz1kAxs3VkJRXbIpls3wVMZXF9KMHo90TO8-Gl21hDlQn02_Te9xt8hERcRytFXFfsMmkvvd5DS-soZSwUZUFLDJD_w\",\"e\":\"AQAB\",\"x5c\":[\"MIICmzCCAYMCBgFwlbVH8TANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZtYXN0ZXIwHhcNMjAwMzAxMTA0NTUwWhcNMzAwMzAxMTA0NzMwWjARMQ8wDQYDVQQDDAZtYXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCskPNv4i3G9ceqvd3wDegKq/kRzmNvomKszDx4rFqT9sOVTk+rjjKcgoyck74Sh6qysxmyFS4jBigLOuG2HsBFT/JAp/1RkaGH5yMsg5qbf4s57qHQxyJLfbH5WSLSJThAJyJuFfcT56lyg0ZfOp1Dvtg2HfFPBB9Gsc++4CSYdUbHUkOqUrwavHbif2ta2vccpj8+hgEQVaMRP7ts+zZcIQ0fMj/YYT2ays7sw6NQhmhaUo+e1bfyi+RUSC/PWQDGzdWQlFdsimWzfBUxlcX0owej3RM7z4aXbWEOVCfTb9N73G3yERFxHK0VcV+wyaS+93kNL6yhlLBRlQUsMkP/AgMBAAEwDQYJKoZIhvcNAQELBQADggEBAHNabEthcvd4IALc6DsmEhtbnPF7ik+7WiCj0v0PhUyGB4Odd1gROg593ZxTf8uHdWaS4ua9k4wmLCCoymTsLO4G6F0xiQU4gxKAJVPrjnwB3SYYcssdEloccW63Ndh66wSCWbSO29L34uM8DUT8j44TIEHOzLFHEW2KLucpxsTxTPU3mBrJWk0uNqZX1AgLb7jHh+H8diBT1tDN9CSbfskMbjI6B7kfejDlBwJNX+sKkWeKfjT9/7wfLg5rYUFXWeVFM4sVMRvGKN2labBaTQocqawBhzm7UBb1Sp3CpkXY3wE0Aw/tl0zv3zqrN/aI3Yy9Xn8cBl/7PInuDlGusxg=\"],\"x5t\":\"TaWdD43wEft07QAHr5WwDDYNRJ4\",\"x5t#S256\":\"vb2Ixb4M0btg6a7QbvV_YQZpHcLPDVfcML-RxqUjIfQ\"}]}",
                "callback": {
                  "scheme": "https",
                  "hostname": "192.168.99.100",
                  "path": "/callback",
                  "port": "32053"
                },
                "client_id": "pkce-test",
                "client_secret": "199c35ad-8e4b-4546-8e18-6f0d158eb364",
                "scopes": ["profile", "User"],
                "cookie_name_prefix": "productpage",
                "id_token": {
                  "preamble": "Bearer",
                  "header": "Authorization"
                },
                "logout": {
                  "path": "/authservice_logout",
                  "redirect_to_uri": "https://keycloak.example.com:8443/auth/realms/master/protocol/openid-connect/logout"
                },
                "max_absolute_session_timeout": 3600,
                "max_session_idle_timeout": 600
              }
            }
          ]
        }
      ]
    }
