apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  acme:
    config:
    - dns01:
        provider: cloud-dns
      domains:
      - www.example.com
      - grpc.example.com
      - example.com
  commonName: example.com
  dnsNames:
  - www.example.com
  - grpc.example.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: istio-ingressgateway-certs