apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: grpc-web-filter
spec:
  workloadLabels:
    app: server
  filters:
  - listenerMatch:
      listenerType: SIDECAR_INBOUND
#      listenerProtocol: HTTP
      listenerProtocol: ALL
# NOTE: filters by port name, prefix your port with grpc-web-
      portNamePrefix: grpc-web
    insertPosition:
      index: AFTER
#      relativeTo: envoy.filters.http.jwt_authn
      relativeTo: envoy.http_connection_manager
    #insertPosition:
    #  index: FIRST
    filterType: HTTP
    filterName: "envoy.grpc_web"
    filterConfig: {}
#    filterConfig:
#      codec_type: auto
#      stat_prefix: ingress_http
#      route_config:
#        name: local_route
#        virtual_hosts:
#        - name: local_service
#          domains: ["*"]
#          routes:
#          - match: { prefix: "/helloworld.Greeter" }
##            route: { cluster: istio-cluster }
#            route:
#              - destination:
##                 host: server.default.svc.cluster.local
#                  host: server
#          cors:
#            allow_origin:
#            - "*"
#            allow_methods: GET, PUT, DELETE, POST, OPTIONS
#            allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,x-csrf-token,authorization,accept
#            max_age: "1728000"
#            expose_headers: custom-header-1,grpc-status,grpc-message
#            enabled: true
#      http_filters:
#      - name: envoy.grpcweb
#      - name: envoy.cors
#      - name: envoy.router