apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-redirect
  namespace: default
spec:
  hosts:
  - keycloak.example.com
  - www.keycloak.example.com
  exportTo:
  - "*"
  ports:
  - number: 8443
    name: https
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
 name: istio-egressgateway
 namespace: default
spec:
 selector:
   istio: egressgateway
 servers:
 - port:
     number: 8443
     name: https
     protocol: HTTPS
  tls:
    mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
   hosts:
   - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-routing
  namespace: default
spec:
  hosts:
  - keycloak.example.com
  - www.keycloak.example.com
  exportTo:
  - "*"
  gateways:
#  - mesh
  - istio-egressgateway
  tls:
  - match:
    - port: 8443
      sni_hosts:
      - keycloak.example.com
    route:
    - destination:
        host: keycloak.example.com
        port:
          number: 8443