apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: www.googleapis.com
spec:
  hosts:
  - "*.googleapis.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloud-sql-instance
spec:
  ports:
  - name: tcp
    number: 3307 # at the moment, Google Cloud SQL always available on port 3307
    protocol: tcp # enable TCP traffic
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: books
spec:
  hosts:
  - "*.googleapis.com"
  - "*.google.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  - number: 80
    name: http
    protocol: HTTP
  resolution: NONE
  location: MESH_EXTERNAL
##---
# Allowing access to Amazon SES
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: smtp
spec:
  hosts:
  - email-smtp.eu-west-1.amazonaws.com
  ports:
  - number: 465
    name: tls
    protocol: tcp
  location: MESH_EXTERNAL
##---
# Amazon SES VirtualService
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: sesservice
spec:
    hosts:
    - email-smtp.eu-west-1.amazonaws.com
    tcp:
    - match:
      - port: 465
      route:
      - destination:
          host: email-smtp.eu-west-1.amazonaws.com
          port:
            number: 465
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-gmail-smtp
spec:
  hosts:
  - 10.150.20.151
  - smtp.gmail.com
  ports:
  - number: 30554
    name: http
    protocol: HTTPS
  - number: 465
    name:  smtp
    protocol: SMTPS
  - number: 587
    name:  tls
  - number: 443
    name:  ssl
  - number: 8080
    name:  ssl1
  - number: 25
    name:  s
  location: MESH_EXTERNAL