apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
    # Note that once we deploy this service over Istio, the grpc- prefix in the Service port name will allow Istio to recognize this as a gRPC service.
  - name: grpc-web
    # see containerPort below
    port: 50051
  selector:
    app: server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      containers:
      - name: server
        # NOTE: replace registry `ip:port` with server address
        image: {{REGISTRY_IP}}/gaeus:server
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
