apiVersion: v1
kind: Service
metadata:
  name: web-ui
  labels:
    app: web-ui
#    run: web-ui
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9001
    targetPort: 9001
  selector:
    app: web-ui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-ui
        version: v1
    spec:
      containers:
      - name: web-ui
        # NOTE: replace registry `ip:port` with server address
        image: {{REGISTRY_IP}}:{{REGISTRY_PORT}}/gaeus:web-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: http
          protocol: TCP
