# Default values for shipments-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
#maxReplicaCount: 2

#resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# hostAliases allows the modification of the hosts file inside a container
hostAliases: []
 # - ip: "xx.xx.xx.xx"
 #   hostnames:
 #   - "xxxxxx.falabella.cl"