#
# A ConfigMap which contains the configuration of the authservice.
# In bookinfo-with-authservice-template.yaml the authservice container is created
# with this ConfigMap volume mounted inside the container at /etc/authservice, which
# is the location where the authservice expects the file to exist.
#

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-authservice-configmap
data:
  config.json: |
    {
      "listen_address": "127.0.0.1",
      "listen_port": "10003",
      "log_level": "trace",
      "threads": 1,
      "chains": [
        {
          "name": "idp_filter_chain",
          "filters": [
          {
            "oidc":
              {
                "authorization": {
                  "scheme": "https",
                  "hostname": "keycloak.example.com",
                  "path": "/auth/realms/master/protocol/openid-connect/auth",
                  "port": "8443"
                },
                "token": {
                  "scheme": "https",
                  "hostname": "keycloak.example.com",
                  "path": "/auth/realms/master/protocol/openid-connect/token",
                  "port": "8443"
                },
                "jwks": "{\"keys\":[{\"kid\":\"8hdOQpGve5Uyg-6lLeL7p8iAbf5wUBpcGSeZ8DBnMlw\",\"kty\":\"RSA\",\"alg\":\"RS256\",\"use\":\"sig\",\"n\":\"rJDzb-ItxvXHqr3d8A3oCqv5Ec5jb6JirMw8eKxak_bDlU5Pq44ynIKMnJO-EoeqsrMZshUuIwYoCzrhth7ARU_yQKf9UZGhh-cjLIOam3-LOe6h0MciS32x-Vki0iU4QCcibhX3E-epcoNGXzqdQ77YNh3xTwQfRrHPvuAkmHVGx1JDqlK8Grx24n9rWtr3HKY_PoYBEFWjET-7bPs2XCENHzI_2GE9msrO7MOjUIZoWlKPntW38ovkVEgvz1kAxs3VkJRXbIpls3wVMZXF9KMHo90TO8-Gl21hDlQn02_Te9xt8hERcRytFXFfsMmkvvd5DS-soZSwUZUFLDJD_w\",\"e\":\"AQAB\",\"x5c\":[\"MIICmzCCAYMCBgFwlbVH8TANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZtYXN0ZXIwHhcNMjAwMzAxMTA0NTUwWhcNMzAwMzAxMTA0NzMwWjARMQ8wDQYDVQQDDAZtYXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCskPNv4i3G9ceqvd3wDegKq/kRzmNvomKszDx4rFqT9sOVTk+rjjKcgoyck74Sh6qysxmyFS4jBigLOuG2HsBFT/JAp/1RkaGH5yMsg5qbf4s57qHQxyJLfbH5WSLSJThAJyJuFfcT56lyg0ZfOp1Dvtg2HfFPBB9Gsc++4CSYdUbHUkOqUrwavHbif2ta2vccpj8+hgEQVaMRP7ts+zZcIQ0fMj/YYT2ays7sw6NQhmhaUo+e1bfyi+RUSC/PWQDGzdWQlFdsimWzfBUxlcX0owej3RM7z4aXbWEOVCfTb9N73G3yERFxHK0VcV+wyaS+93kNL6yhlLBRlQUsMkP/AgMBAAEwDQYJKoZIhvcNAQELBQADggEBAHNabEthcvd4IALc6DsmEhtbnPF7ik+7WiCj0v0PhUyGB4Odd1gROg593ZxTf8uHdWaS4ua9k4wmLCCoymTsLO4G6F0xiQU4gxKAJVPrjnwB3SYYcssdEloccW63Ndh66wSCWbSO29L34uM8DUT8j44TIEHOzLFHEW2KLucpxsTxTPU3mBrJWk0uNqZX1AgLb7jHh+H8diBT1tDN9CSbfskMbjI6B7kfejDlBwJNX+sKkWeKfjT9/7wfLg5rYUFXWeVFM4sVMRvGKN2labBaTQocqawBhzm7UBb1Sp3CpkXY3wE0Aw/tl0zv3zqrN/aI3Yy9Xn8cBl/7PInuDlGusxg=\"],\"x5t\":\"TaWdD43wEft07QAHr5WwDDYNRJ4\",\"x5t#S256\":\"vb2Ixb4M0btg6a7QbvV_YQZpHcLPDVfcML-RxqUjIfQ\"}]}",
                "callback": {
                  "scheme": "https",
                  "hostname": "{{ .Values.INGRESS_HOST }}",
                  "path": "/callback",
                  "port": "{{ .Values.INGRESS_PORT }}"
                },
                "client_id": "pkce-test",
                "client_secret": "199c35ad-8e4b-4546-8e18-6f0d158eb364",
                "scopes": ["profile", "User"],
                "cookie_name_prefix": "productpage",
                "id_token": {
                  "preamble": "Bearer",
                  "header": "Authorization"
                },
                "logout": {
                  "path": "/authservice_logout",
                  "redirect_to_uri": "https://keycloak.example.com:8443/auth/realms/master/protocol/openid-connect/logout"
                },
                "max_absolute_session_timeout": 3600,
                "max_session_idle_timeout": 600,
                "trusted_certificate_authority": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDda3erJG5jSi2r\nA9k6oY3d8Dlfz9CNwRwHTEpwLajAVh0SWZwKuj3ZnlsIBpQWrHCEG8lxprOUQmbL\nwY4C6rlbMgsnsxlEUgZPH4+QJPy9EF+EbZM5xro9eQ18T4DbA3cpfQlcUfXI5YrV\nWyDoSsjSBMNuYVCp/3jW+UpjuqtUn35jz1SUHSt2btH6wZk+zfWxjxUjCRQ+1UDx\neSJEzeinzF+TkT/nhfRoB3MCBQS3UU9xJCSiWRt+k+ay0rTF5cmr+M+ZiII9fXah\nOMYh9bX3+2HLYOyjdNjjpU8oyzESRjCArvnYEfjT6YRt/cPOx6VmGIC1oG9pATif\nAF/ibM4NAgMBAAECggEBAK/fpPYzwdrsGMo2DF4d5Onc3jXUg/uU4AaL+rSQD/J2\ndDEXLHL47BfnSLdfQlGgNt84kxHLL+kbtTszSvHWL9TYMzQddnxmCszebNI6Dua+\nEqDFyKOjzlr1xFhxbhCI+CXkQ4MpNumUKmq+L61TeaAYWINcmQ3u9rUK3qPIqj5T\n1ucmF62ZKlzLiF/aIfWIF+IsmKhaSe5yjxi7vDGuzbx9g/7zvP8QoAVyINrR8Ba9\nO2x1e1iQhPt3pAlzqFVTLGrciqvyfWx7QsTFdVHPkAh3S6FeqC3Cv90twk1T7XWW\nXwXWCmTWZXJrvD8+syCnisT53LoG9bN+wV9nwGsk9wECgYEA+9CKyBy8dxmLl8v5\nJ9XwhzFB6xWJ7++uaE8PXp+/2Pjrmf6Y+HD37SRasCYzPijG6Qzk4cf7qDMF1CVm\ncv161O3xNztCvtDL8A02zlOZEvkQ/u2W3tZE1Zx6Ztpd5NyBsfGIbyippiLBs3Ed\neO4zPfLayzALo8gCgrHfAwSSw6kCgYEA4RmY01fIIrBDoTQU9GvEJbT1asklCW9P\nxjTAm5FUaHZd1qJtGzB1Z5Vq3wrwDgnQJKRy/0XKKkGeNInsRJJD/6ZXRn6gNFeG\nIofZjZ/+IKeeUUbwmgjvHBpyeTpfALRuRdioBBTJ4WvyW1b+py1m6Fo8ZwPP964d\nBQNke0OQdcUCgYEAqTFrrh0wvE1br7iLRirHG+8KvWuRbLd8VfWY/BkWDDDkDGo2\nWed9jca5cFWaZI99ZqUVPGbkPhVaOzqN5YFPALaHNncI17Du9fHK+0LMPSVAOCln\nD36kbWpgC695GwbV1bvV0epeYpRD1c+Q3+ocX+lG/PLhP0Bp/2qHzz1JZ1ECgYEA\n1vGOUSEdZqJRsfj9mXfeUPM+9b0ktKGp12ZAFUztAOMmL/HhpXjcYxD2gAz9tSoB\nqzus471MkpUd8KVTCxdv/wpjhFkduV1qJEb8opQIIj5smsfWr/+f84H9lWz7kry4\nH9IGff8r1ykwv6+OcyyTe4PO8b9eMu/7nfHjXSDjLNECgYBwbcnNcNDsnyRjlIve\nNLdZKSIrsIl8k6qEDVkxafEMhDua+NZk2PIMgwPeJkCOg9lFoGGRvSg4yGGVZDVK\nNxqM7TWl3rWY9LFs+Y8D51JbuNVabee2fdb48He6sGGHmHHRyRMnotmmdmnscms4\nsjZ5XAL0+AZvGg75rcCKYFxa9A==\n-----END PRIVATE KEY-----\n"
              }
            }
          ]
        }
      ]
    }
