#
# A ConfigMap which contains the configuration of the authservice.
# In bookinfo-with-authservice-template.yaml the authservice container is created
# with this ConfigMap volume mounted inside the container at /etc/authservice, which
# is the location where the authservice expects the file to exist.
#

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-authservice-configmap
data:
  config.json: |
    {
      "listen_address": "127.0.0.1",
      "listen_port": "10003",
      "log_level": "trace",
      "threads": 8,
      "chains": [
        {
          "name": "idp_filter_chain",
          "filters": [
          {
            "oidc":
              {
                "authorization": {
                  "scheme": "https",
                  "hostname": "keycloak.example.com",
                  "path": "/auth/realms/master/protocol/openid-connect/auth",
                  "port": "8443"
                },
                "token": {
                  "scheme": "https",
                  "hostname": "keycloak.example.com",
                  "path": "/auth/realms/master/protocol/openid-connect/token",
                  "port": "8443"
                },
                "jwks": "{\"keys\":[{\"kid\":\"sCdb0aOyizSf4Fmx1pGnn4ey-_bdSmzNcT_IGn54x68\",\"kty\":\"RSA\",\"alg\":\"RS256\",\"use\":\"sig\",\"n\":\"ywiOUuqfAsdRwOpQ8aGXv8wni1MKZytNCoiW_6EltTBbG0g1OMsQyO82Zj8j3jlVR5vSTwouMXAIAomBsrTAn-Rw2hvFsNOXoQlyJ-_c8KiSeS3sf4bEcyVa0AOpMH6GTqaZESOMf4CQo2R9O9oQ_xFWG3_qrthQUhmTEAFa-haBfyK6cWXnGqBW048XyGrqrymrrDp_xei_uq1kBGiMN1E3c_weREABkcC73VbkqgwOXdNpzkr9R3AsWWz9lqhAOORS19j9XWUEbjbstlN0qWAoqQFlGE16WgpJx8S36AzXdux-qWXkblD0OiBwS7pPHtSQhNPfEvyQ7fV_fqWovw\",\"e\":\"AQAB\",\"x5c\":[\"MIICmzCCAYMCBgFwjCxR6jANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAZtYXN0ZXIwHhcNMjAwMjI4MTQxOTM5WhcNMzAwMjI4MTQyMTE5WjARMQ8wDQYDVQQDDAZtYXN0ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDLCI5S6p8Cx1HA6lDxoZe/zCeLUwpnK00KiJb/oSW1MFsbSDU4yxDI7zZmPyPeOVVHm9JPCi4xcAgCiYGytMCf5HDaG8Ww05ehCXIn79zwqJJ5Lex/hsRzJVrQA6kwfoZOppkRI4x/gJCjZH072hD/EVYbf+qu2FBSGZMQAVr6FoF/IrpxZecaoFbTjxfIauqvKausOn/F6L+6rWQEaIw3UTdz/B5EQAGRwLvdVuSqDA5d02nOSv1HcCxZbP2WqEA45FLX2P1dZQRuNuy2U3SpYCipAWUYTXpaCknHxLfoDNd27H6pZeRuUPQ6IHBLuk8e1JCE098S/JDt9X9+pai/AgMBAAEwDQYJKoZIhvcNAQELBQADggEBADZ88AhB/JGIlhqVStm6fAWQZoOsqFqREmZB8pPNOTVykMsE8uxqOnNC8OWpP3+6w6JNTLZuJX1LgZg3PyiMPGSSjrI6m/JuadharKGxxyk3AlAJ369c0anPQhucxFHbYNDDOP3/TnW/Re0vYlGfPuaVpPzUS8YkQglVbWU/C2Ja5hvxiewIAi94TQBdFIE48PQTC+qVg2T+thCYV+QSRU9Fm6vKtQgQySSut6LsR82kS91KK57dmkqDSobp3Ir2U0hfLfzlIZ9XwPmLyK9KLVYwPkMi4pFdM2++18z1UTaSOVrXJeggymtZB8dzl70QA236mU1fgAYEg7g7b6PNPbc=\"],\"x5t\":\"o3_283A0nrypXG__wPY6Ker4UEY\",\"x5t#S256\":\"1bKd3G-bB-r-S8Gw11qcdkz64FhlmX2ghGGK7kkM5Ik\"}]}",
                "callback": {
                  "scheme": "https",
                  "hostname": "{{ .Values.INGRESS_HOST }}",
                  "path": "/productpage/oauth/callback",
                  "port": "{{ .Values.INGRESS_PORT }}"
                },
                "client_id": "pkce-test",
                "client_secret": "72e0146a-de99-4bcc-b77d-4d591bdb32eb",
                "scopes": ["openid", "profile", "User"],
                "landing_page": "https://{{ .Values.INGRESS_HOST }}:{{ .Values.INGRESS_PORT }}/",
                "cryptor_secret": "app_secret_xxx",
                "cookie_name_prefix": "productpage",
                "id_token": {
                  "preamble": "Bearer",
                  "header": "Authorization"
                },
                "timeout": 300,
                "logout": {
                  "path": "/authservice_logout",
                  "redirect_to_uri": "https://keycloak.example.com:8443/auth/realms/master/protocol/openid-connect/logout"
                }
              }
            }
          ]
        }
      ]
    }
